"""empty message

Revision ID: 786053002a81
Revises: 9dc46a2bc0fb
Create Date: 2026-06-29 20:48:34.336383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "786053002a81"
down_revision: Union[str, None] = "9dc46a2bc0fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_tokens", "session_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    op.drop_constraint("user_tokens_session_id_fkey", "user_tokens", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "user_tokens_session_id_fkey",
        "user_tokens",
        "user_sessions",
        ["session_id"],
        ["session_id"],
    )
    op.alter_column(
        "user_tokens", "session_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    # ### end Alembic commands ###
